// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jyxhgcfpgwyidtbmuoqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp5eGhnY2ZwZ3d5aWR0Ym11b3F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1OTIxMTEsImV4cCI6MjA2MDE2ODExMX0.rIq7zEDE5mos0Hi7Hhg59Kih3g4iN_coTtEMptdlx74";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);